### ISSUE TITLE
Build from source to make compatible for Elasticsearch 7.6.2

### ISSUE THREAD

**Issue by fadjar340** [opendistro-for-elasticsearch/sql-jdbc#78]
Hi there,

Is there any documentation that explain how to build from source to make OD 1.6.0 compatible with Elasticsearch 7.6.2?

Regards,
Fadjar Tandabawana

**Comment by anirudha** [comment]
https://github.com/opendistro-for-elasticsearch/sql-jdbc/tree/opendistro-1.6

You can build from this branch

**Comment by anirudha** [comment]
Please reopen this issue if you have questions

**Comment by fadjar340** [comment]
After build from source, I have the opendistro_sql-1.7.0.0-SNAPSHOT.jar, then I use it in dbeaver.
The problem is the same, bad request, since I saw in [https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/](https://opendistro.github.io/for-elasticsearch-docs/docs/install/plugins/), it should install the opendistro-sql-xxx.zip, when I following the URL, the result said that the plugins for 7.6.1.
How I can use it in 7.6.2? Please give a hint...

Regards,
Fadjar Tandabawana

**Comment by penghuo** [comment]
You should build the plugin https://github.com/opendistro-for-elasticsearch/sql to make it compatible with Elasticsearch 7.6.2. [Here is the code.](https://github.com/opendistro-for-elasticsearch/sql/blob/master/build.gradle#L18) 
Because JDBC just use RESTful enpoint, there should be no change regarding to JDBC.
